export const ALL_EMPLOYEES_REQUEST = "ALL_EMPLOYYES_REQUEST";
export const ALL_EMPLOYEES_SUCCESS = "ALL_EMPLOYEES_SUCCESS";
export const ALL_EMPLOYEES_FAIL = "ALL_EMPLOYYES_FAIL";

export const SET_EMPLOYEE = "SET_EMPLOYEE";
